debugging

diff --git a/.github/workflows/dev-deploy.yml b/.github/workflows/dev-deploy.yml
--- a/.github/workflows/dev-deploy.yml
+++ b/.github/workflows/dev-deploy.yml
@@ -17,7 +17,7 @@ env:
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
 jobs:
-  test:
+  test-and-deploy:
     runs-on: ubuntu-latest
 
     steps:
@@ -45,55 +45,27 @@ jobs:
             exit 1
           fi
 
+      - name: Check test coverage
+        run: |
+          if [ -f ./coverage/coverage-summary.json ]; then
+            COVERAGE=$(cat ./coverage/coverage-summary.json | jq .total.lines.pct)
+            echo "Test coverage is ${COVERAGE}%"
+            if (( $(echo "$COVERAGE < 90" | bc -l) )); then
+              echo "⚠️ Test coverage is below 90%, but proceeding with deployment."
+            fi
+          else
+            echo "❌ coverage-summary.json NOT FOUND!"
+            exit 1
+          fi
+
+      - name: Debug coverage directory
+        run: ls -R ./coverage
+
       - name: Upload coverage report
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v3.2.1  # Usa l'ultima versione disponibile
         with:
           name: coverage-report
           path: coverage/
-
-  check-coverage:
-    runs-on: ubuntu-latest
-    needs: test
-
-    steps:
-      - name: Check out the repository
-        uses: actions/checkout@v4
-
-      - name: Download coverage report
-        uses: actions/download-artifact@v3
-        with:
-          name: coverage-report
-
-      - name: Install utilities
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y jq bc
-
-      - name: Check if coverage-summary.json exists
-        run: |
-          echo "Listing coverage files for verification:"
-          ls ./coverage
-          if [ ! -f ./coverage/coverage-summary.json ]; then
-            echo "❌ Coverage report not found!"
-            exit 1
-          fi
-          echo "✅ Coverage report found"
-
-      - name: Check test coverage
-        run: |
-          COVERAGE=$(cat ./coverage/coverage-summary.json | jq .total.lines.pct)
-          echo "Test coverage is ${COVERAGE}%"
-          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
-            echo "⚠️ Test coverage is below 90%, but proceeding with deployment."
-          fi
-
-  deploy:
-    runs-on: ubuntu-latest
-    needs: check-coverage
-
-    steps:
-      - name: Check out the repository
-        uses: actions/checkout@v4
 
       - name: Build the project
         run: npm run build
